const KEY='casa-em-ordem-v1';
const DEFAULT_CATEGORIES={
  'Despensa':['Alimentos','Bebidas','Limpeza','Higiene','Outros'],
  'Beleza':['Efeitos','Neutros','Nudes','Rosas','Vermelhos','Roxos','Azuis','Verdes','Cuidados','Consumíveis','Utensílios','Hidratantes mãos','Hidratantes corpo','Hidratante lábios','Protetor solar lábios','Protetor solar corpo','Pós-sol','Perfumes','Desodorantes','Máscaras','Sabonete antiacne','Tônicos','Calmantes','Hidratante','Hidratante antiacne','Protetor solar','Anti-idade','Clareadores','Tratamento','Primer','Corretivo','Base e BBcream','Pó','Blush','Contorno, iluminador e bronzer','Sombra','Lápis e delineador','Máscara cílios','Batom','Demaquilante/Fixador','Pincéis e esponjas','Prendedores','Shampoo','Condicionador','Cremes','Finalizadores','Esmaltes','Unhas','Cosméticos','Skincare','Maquiagem','Cabelo'],
  'Remédios':['Gastrointestinais','Analgésicos','Antiparasitários','Antimicóticos','Gripes e resfriados','Vitaminas','Estimulante','Hormônios','Antiinflamatórios','Antibióticos','Hidratantes','Antivirais','Colírios','Antissépticos','Ataduras','Medicamentos','Pomadas','Gotas','Primeiros socorros']
};
const START_PLACES=['Cozinha','Banheiro','Área de serviço','Quarto','Farmácia'];
const el=id=>document.getElementById(id);
let state=loadState(), activeType='', photoData='', toastTimer;
function loadState(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');return {items:s.items||[],places:s.places||START_PLACES,categories:{...DEFAULT_CATEGORIES,...(s.categories||{})},updatedAt:s.updatedAt||null};}catch{return {items:[],places:START_PLACES,categories:DEFAULT_CATEGORIES,updatedAt:null}}}
function persist(){state.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){notify('Armazenamento cheio. Remova algumas fotos ou configure a sincronização.');}render();if(session?.access_token)syncPush();}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function notify(text){const t=el('toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function fmtDate(s){if(!s)return '';const d=new Date(s+'T12:00:00');return Number.isNaN(d.valueOf())?'':d.toLocaleDateString('pt-BR')}
function render(){renderStats();renderFilters();renderItems();el('navCount').textContent=state.items.length;}
function renderStats(){const today=new Date();today.setHours(0,0,0,0);const thirty=new Date(today);thirty.setDate(thirty.getDate()+30);el('statItems').textContent=state.items.length;el('statPlaces').textContent=new Set(state.items.map(i=>i.place).filter(Boolean)).size;el('statLow').textContent=state.items.filter(i=>i.minimum!==''&&Number(i.quantity)<=Number(i.minimum)).length;el('statExpiry').textContent=state.items.filter(i=>i.expiry&&new Date(i.expiry+'T00:00:00')>=today&&new Date(i.expiry+'T00:00:00')<=thirty).length;}
function renderFilters(){const place=el('placeFilter'), selected=place.value;place.innerHTML='<option value="">Todos os locais</option>'+state.places.map(p=>`<option>${escapeHtml(p)}</option>`).join('');if(state.places.includes(selected))place.value=selected;const c=el('itemCategory'), old=c.value;c.innerHTML='<option value="">Selecione</option>'+[...(state.categories[el('itemType').value]||[])].map(x=>`<option>${escapeHtml(x)}</option>`).join('');if((state.categories[el('itemType').value]||[]).includes(old))c.value=old;const p=el('itemPlace'),v=p.value;p.innerHTML=state.places.map(x=>`<option>${escapeHtml(x)}</option>`).join('');if(state.places.includes(v))p.value=v;}
function renderItems(){const q=el('searchInput').value.trim().toLocaleLowerCase('pt-BR'),type=el('typeFilter').value,place=el('placeFilter').value,sort=el('sortFilter').value;let items=state.items.filter(i=>(!type||i.type===type)&&(!activeType||i.type===activeType)&&(!place||i.place===place)&&(!q||[i.name,i.brand,i.category,i.place,i.notes].join(' ').toLocaleLowerCase('pt-BR').includes(q)));items.sort((a,b)=>sort==='quantity'?Number(a.quantity)-Number(b.quantity):sort==='expiry'?(a.expiry||'9999').localeCompare(b.expiry||'9999'):sort==='recent'?(b.createdAt||'').localeCompare(a.createdAt||''):a.name.localeCompare(b.name,'pt-BR'));const grid=el('itemsGrid');grid.innerHTML=items.map(itemCard).join('');el('emptyState').classList.toggle('hidden',items.length>0);grid.classList.toggle('hidden',!items.length);}
function itemCard(i){const low=i.minimum!==''&&Number(i.quantity)<=Number(i.minimum),exp=i.expiry?Math.ceil((new Date(i.expiry+'T00:00:00')-new Date(new Date().setHours(0,0,0,0)))/86400000):null;let pill=i.type==='Beleza'?'Beauty':i.type==='Remédios'?'Medicine':'';return `<article class="item-card"><div class="item-photo">${i.photo?`<img src="${i.photo}" alt="${escapeHtml(i.name)}">`:'◫'}</div><div class="item-head"><div class="item-name" title="${escapeHtml(i.name)}">${escapeHtml(i.name)}</div><button class="dots-btn" data-edit="${i.id}" aria-label="Editar ${escapeHtml(i.name)}">···</button></div><span class="type-pill ${pill}">${escapeHtml(i.type)}${i.category?' · '+escapeHtml(i.category):''}</span><div class="item-meta"><span>Quantidade</span><b>${escapeHtml(i.quantity)} ${escapeHtml(i.unit)}</b></div><div class="item-meta"><span>Local</span><b>${escapeHtml(i.place)}</b></div>${i.brand?`<div class="item-meta"><span>Marca</span><b>${escapeHtml(i.brand)}</b></div>`:''}<div class="item-footer"><span class="${exp!==null&&exp<=30?'expiry-warn':''}">${i.expiry?(exp<0?'Vencido em ':exp===0?'Vence hoje · ':`Validade · `)+fmtDate(i.expiry):'Sem validade informada'}</span>${low?'<span class="low-badge">ESTOQUE BAIXO</span>':''}</div></article>`}
function openItem(item){el('itemForm').reset();el('itemId').value=item?.id||'';el('modalTitle').textContent=item?'Editar item':'Adicionar item';el('itemName').value=item?.name||'';el('itemType').value=item?.type||'Despensa';el('itemQuantity').value=item?.quantity??1;el('itemUnit').value=item?.unit||'unidade(s)';el('itemMinimum').value=item?.minimum??'';el('itemExpiry').value=item?.expiry||'';el('itemBrand').value=item?.brand||'';el('itemNotes').value=item?.notes||'';photoData=item?.photo||'';renderFilters();el('itemCategory').value=item?.category||'';el('itemPlace').value=item?.place||state.places[0];setPhoto();const actions=el('itemForm').querySelector('.modal-actions');let del=el('deleteItem');if(del)del.remove();if(item){del=document.createElement('button');del.type='button';del.id='deleteItem';del.className='secondary-btn';del.style.marginRight='auto';del.textContent='Excluir item';del.onclick=()=>{if(confirm(`Excluir “${item.name}”?`)){state.items=state.items.filter(i=>i.id!==item.id);persist();closeItem();notify('Item excluído')}};actions.prepend(del)}el('modalOverlay').classList.remove('hidden');el('itemName').focus();}
function closeItem(){el('modalOverlay').classList.add('hidden')}
function setPhoto(){el('photoPreview').src=photoData;el('photoPreview').classList.toggle('hidden',!photoData);el('photoPlaceholder').classList.toggle('hidden',!!photoData);el('removePhoto').classList.toggle('hidden',!photoData)}
el('itemForm').addEventListener('submit',e=>{e.preventDefault();const id=el('itemId').value,old=state.items.find(i=>i.id===id);const item={id:id||crypto.randomUUID(),name:el('itemName').value.trim(),type:el('itemType').value,category:el('itemCategory').value,place:el('itemPlace').value,quantity:el('itemQuantity').value,unit:el('itemUnit').value,minimum:el('itemMinimum').value,expiry:el('itemExpiry').value,brand:el('itemBrand').value.trim(),notes:el('itemNotes').value.trim(),photo:photoData,createdAt:old?.createdAt||new Date().toISOString()};state.items=old?state.items.map(i=>i.id===id?item:i):[item,...state.items];persist();closeItem();notify(old?'Item atualizado':'Item adicionado');});
el('photoDrop').addEventListener('click',e=>{if(e.target.id!=='removePhoto')el('photoInput').click()});el('photoInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(!file.type.startsWith('image/'))return notify('Escolha uma imagem.');const img=new Image(),reader=new FileReader();reader.onload=()=>{img.onload=()=>{const ratio=Math.min(1,1000/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*ratio);canvas.height=Math.round(img.height*ratio);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);photoData=canvas.toDataURL('image/jpeg',.72);setPhoto();};img.src=reader.result;};reader.readAsDataURL(file)});el('removePhoto').addEventListener('click',e=>{e.stopPropagation();photoData='';el('photoInput').value='';setPhoto()});
el('itemType').addEventListener('change',()=>renderFilters());['closeModal','cancelModal'].forEach(id=>el(id).addEventListener('click',closeItem));el('modalOverlay').addEventListener('click',e=>{if(e.target===el('modalOverlay'))closeItem()});
el('itemsGrid').addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(!b)return;const item=state.items.find(i=>i.id===b.dataset.edit);if(item)openItem(item)});
['searchInput','typeFilter','placeFilter','sortFilter'].forEach(id=>el(id).addEventListener('input',renderItems));
document.querySelectorAll('.nav-item[data-page="estoque"]').forEach(b=>b.addEventListener('click',()=>{activeType=b.dataset.filter||'';el('typeFilter').value='';el('listTitle').textContent=activeType||'Seus itens';document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));b.classList.add('active');renderItems();el('sidebar').classList.remove('open')}));
function manage(which){const isPlaces=which==='places',title=isPlaces?'Locais da casa':'Categorias',lists=isPlaces?state.places:state.categories[el('itemType').value]||[],body=`<p style="font-size:11px;color:#879188;line-height:1.5;margin:-7px 0 13px">${isPlaces?'Cadastre os cômodos, armários e outros pontos de armazenamento.':'Categorias para '+el('itemType').value+'. Use nomes que ajudem a encontrar seus itens.'}</p><div class="manage-list">${lists.map((x,n)=>`<div class="manage-row"><span>${escapeHtml(x)}</span><small>${isPlaces?state.items.filter(i=>i.place===x).length+' itens':''}</small><button type="button" data-remove="${n}" aria-label="Remover">Remover</button></div>`).join('')||'<p style="font-size:11px;color:#98a198">Nenhum registro ainda.</p>'}</div><div class="inline-add"><input id="manageInput" placeholder="${isPlaces?'Ex.: Despensa':'Ex.: Limpeza'}" maxlength="50"><button id="manageAdd">＋ Adicionar</button></div>`;el('simpleTitle').textContent=title;el('simpleEyebrow').textContent=isPlaces?'LOCAIS':'CATEGORIAS';el('simpleContent').innerHTML=body;el('simpleOverlay').classList.remove('hidden');el('manageAdd').onclick=()=>{const v=el('manageInput').value.trim();if(!v)return;if(isPlaces){if(!state.places.includes(v))state.places.push(v)}else{const cats=state.categories[el('itemType').value]||(state.categories[el('itemType').value]=[]);if(!cats.includes(v))cats.push(v)}persist();manage(which)};el('manageInput').onkeydown=e=>{if(e.key==='Enter')el('manageAdd').click()};el('simpleContent').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.remove);if(isPlaces){const v=state.places[n];if(state.items.some(i=>i.place===v))return notify('Mova os itens deste local antes de removê-lo.');state.places.splice(n,1)}else state.categories[el('itemType').value].splice(n,1);persist();manage(which)});}
el('manageBtn').onclick=()=>manage('places');document.querySelector('[data-page="locais"]').onclick=()=>{manage('places');el('sidebar').classList.remove('open')};document.querySelector('[data-page="categorias"]').onclick=()=>{manage('categories');el('sidebar').classList.remove('open')};el('closeSimple').onclick=()=>el('simpleOverlay').classList.add('hidden');el('simpleOverlay').addEventListener('click',e=>{if(e.target===el('simpleOverlay'))el('simpleOverlay').classList.add('hidden')});
el('addItemBtn').onclick=()=>openItem();el('emptyAddBtn').onclick=()=>openItem();el('menuToggle').onclick=()=>el('sidebar').classList.toggle('open');
el('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='casa-em-ordem-backup.json';a.click();URL.revokeObjectURL(a.href);notify('Backup baixado')};

let session=JSON.parse(localStorage.getItem('casa-supabase-session')||'null');const conf=()=>({url:localStorage.getItem('casa-supabase-url')||'',key:localStorage.getItem('casa-supabase-key')||''});function setSyncStatus(ok,msg){el('syncTitle').textContent=ok?'Supabase conectado':'Dados neste aparelho';el('syncSubtitle').textContent=msg;document.querySelector('.sync-dot').style.background=ok?'#74a97b':'#d4a65d'}
async function authRequest(path,body){const c=conf();return fetch(c.url.replace(/\/$/,'')+'/auth/v1/'+path,{method:'POST',headers:{'Content-Type':'application/json','apikey':c.key},body:JSON.stringify(body)})}
async function refreshSession(){if(!session?.refresh_token)throw new Error('Entre novamente na sua conta Supabase.');const r=await authRequest('token?grant_type=refresh_token',{refresh_token:session.refresh_token}),j=await r.json();if(!r.ok)throw new Error('Sua sessão expirou. Entre novamente.');session=j;localStorage.setItem('casa-supabase-session',JSON.stringify(session))}
async function apiFetch(path,options={}){const c=conf(),url=c.url.replace(/\/$/,'')+path;const send=()=>fetch(url,{...options,headers:{...(options.headers||{}),apikey:c.key,...(session?.access_token?{Authorization:'Bearer '+session.access_token}:{})}});let response=await send();if(response.status===401&&session?.refresh_token){await refreshSession();response=await send()}return response}
async function dbRequest(method,body){const path='/rest/v1/home_inventory?user_id=eq.'+encodeURIComponent(session.user.id);const resp=await apiFetch(path,{method,headers:{'Content-Type':'application/json','Prefer':method==='POST'?'resolution=merge-duplicates,return=minimal':'return=minimal'},...(body?{body:JSON.stringify(body)}:{})});if(!resp.ok)throw new Error('Não foi possível sincronizar. Confira o SQL e as credenciais.')}
async function syncPush(){try{await dbRequest('POST',{user_id:session.user.id,data:state,updated_at:state.updatedAt});setSyncStatus(true,'Atualizado agora')}catch(e){setSyncStatus(false,'Falha na sincronização');console.warn(e)}}
async function connectSync(){if(!session?.access_token)return;try{const r=await apiFetch('/rest/v1/home_inventory?user_id=eq.'+encodeURIComponent(session.user.id)+'&select=data');if(!r.ok)throw new Error('A conexão Supabase falhou. Confira a configuração da tabela.');const rows=await r.json();if(rows[0]?.data){const remote=rows[0].data;if(!state.updatedAt||new Date(remote.updatedAt)>new Date(state.updatedAt)){state=remote;localStorage.setItem(KEY,JSON.stringify(state));render()}else await syncPush()}else await syncPush();setSyncStatus(true,'Sincronizado com sua conta')}catch(e){setSyncStatus(false,'Confira a configuração');notify(e.message)}}
function settings(){const c=conf();el('simpleEyebrow').textContent='PREFERÊNCIAS';el('simpleTitle').textContent='Configurações';el('simpleContent').innerHTML=`<div class="setting-block"><h3>Sincronização entre aparelhos</h3><p>Conecte seu projeto Supabase para acessar os mesmos itens no computador e no celular. Configure a tabela no SQL incluído na pasta e use uma conta de acesso.</p><input class="setting-input" id="sbUrl" placeholder="URL do projeto Supabase" value="${escapeHtml(c.url)}"><input class="setting-input" id="sbKey" placeholder="Chave anon / publishable" value="${escapeHtml(c.key)}"><div class="setting-row"><input class="setting-input" id="sbEmail" type="email" placeholder="Seu e-mail" value="${escapeHtml(session?.user?.email||'')}"><input class="setting-input" id="sbPass" type="password" placeholder="Senha"></div><div class="modal-actions" style="margin-top:12px"><button class="secondary-btn" id="sbSignup">Criar conta</button><button class="primary-btn" id="sbLogin">Entrar e sincronizar</button></div><p id="sbMessage" style="margin-top:8px"></p></div><div class="setting-block"><h3>Backup e privacidade</h3><p>Os dados ficam neste navegador enquanto a sincronização não estiver configurada. Fotos são reduzidas antes de salvar. Use o botão de download no topo para guardar uma cópia.</p>${session?'<button class="secondary-btn" id="sbLogout">Desconectar conta</button>':''}</div>`;el('simpleOverlay').classList.remove('hidden');function saveConf(){localStorage.setItem('casa-supabase-url',el('sbUrl').value.trim());localStorage.setItem('casa-supabase-key',el('sbKey').value.trim())}el('sbSignup').onclick=async()=>{saveConf();try{const r=await authRequest('signup',{email:el('sbEmail').value,password:el('sbPass').value});const j=await r.json();if(!r.ok)throw Error(j.msg||j.message||j.error_description||'Não foi possível criar a conta');if(j.access_token){session=j;localStorage.setItem('casa-supabase-session',JSON.stringify(session));await connectSync()}else notify('Confirme seu e-mail e depois entre na conta.')}catch(e){notify(e.message)}};el('sbLogin').onclick=async()=>{saveConf();try{const r=await authRequest('token?grant_type=password',{email:el('sbEmail').value,password:el('sbPass').value}),j=await r.json();if(!r.ok)throw Error(j.msg||j.message||j.error_description||'E-mail ou senha inválidos');session=j;localStorage.setItem('casa-supabase-session',JSON.stringify(session));await connectSync();el('simpleOverlay').classList.add('hidden')}catch(e){notify(e.message)}};if(el('sbLogout'))el('sbLogout').onclick=()=>{session=null;localStorage.removeItem('casa-supabase-session');setSyncStatus(false,'Sincronização desativada');settings()}}
el('settingsBtn').onclick=settings;render();if(session?.access_token&&conf().url&&conf().key)connectSync();
